version: '3.9'

services:
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - crm-network
    redis:
        container_name: redis
        image: redis:latest
        restart: always
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
        ports:
            - '${REDIS_PORT}:${REDIS_PORT}'
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - crm-network

volumes:
    postgres_data:
    redis_data:

networks:
    crm-network:
